export const translations: Record<string, any> = {
  '中文': {
    nav: { home: '首页', product: '产品中心', cases: '案例中心', about: '关于我们', contact: '联系我们' },
    hero: { title1: 'AI+能源驱动的', title2: '“零碳新质生产力”运营商', btn1: '探索解决方案', btn2: '了解我们' },
    product: { title: 'AethraGrid', subtitle: 'AI能源管理云平台', tab1: '1+5 产品矩阵', tab1Desc: '以 AethraCore AI 模型为核心，端-边-云架构驱动能源数字化转型。涵盖智能微网管理、虚拟电厂调度、碳资产管理、能效优化控制及设备预测性维护五大核心模块，实现能源全链路的智能化闭环。', tab2: '六维建设体系', tab2Desc: '科学算碳、源头减碳、过程脱碳、智能控碳、协同降碳、抵消披露。构建全生命周期的碳管理体系，从底层数据采集到顶层战略规划，赋能企业实现零碳转型。', efficiency: '系统运行效率', carbon: '实时碳减排', ai: 'AI 调度中', compare: '较上月提升 12%' },
    cases: { title: '案例中心', subtitle: '全球化标杆项目落地', c1: '光储一体化项目', c1c: '零碳工厂', c1d: '通过部署“光储一体化 + AI调度系统”方案，实现削峰填谷与电价套利，显著降低用电成本。', c2: '绿电 + 水蓄冷项目', c2c: '零碳工厂', c2d: '采用“绿电 + 水蓄冷 + AI调度”综合方案，降低制冷系统用能成本，提升绿色电力使用比例。', c3: '光伏 + 污水处理协同项目', c3c: '零碳园区', c3d: '采用“光伏 + 负荷协同调度”模式，降低运营成本，打造绿色低碳示范园区。', c4: '德国综合体光储充一体化项目', c4c: '零碳园区', c4d: '采用“光储充一体化 + AI调度”系统，实现能源自给率提升，满足欧洲绿色合规标准。' },
    data: { title: '价值创造', subtitle: '用数据定义零碳新质生产力', s1: '累计运营可再生能源资产', s2: '累计节约电能', s3: '累计减少碳排放', desc: '我们不仅提供能源解决方案，更构建可持续发展的底层能源能力。' },
    map: { title: '全球布局', subtitle: '业务覆盖网络', cn: '中国', us: '美国', de: '德国', vn: '越南', th: '泰国', au: '澳大利亚' },
    about: { title: '关于我们', vTitle: '核心愿景', vDesc: '以优质负荷为核心，以AI为引擎，成为全球领先的零碳新质生产力运营商。', pTitle: '核心定位', pDesc: 'AI+数据驱动的“零碳新质生产力”能源运营商', fTitle: '聚焦领域', f1: '低碳绿能', f2: '能源精益运营', f3: 'ESG价值创造', cTitle: '客户价值', c1: '省成本', c2: '创营收', c3: '高效率', c4: 'ESG标杆' },
    footer: { desc: '用可再生能源与AI技术驱动能源低碳未来', links: '快速链接', hq: '全球总部', sz: '中国 · 深圳', szDesc: '广东省深圳市南山区\n清华信息港科研楼', ca: '美国 · 加州', caDesc: 'San Diego, California\nUSA', rights: '© 2025 AethraVolt 合擎源动. All rights reserved.', privacy: '隐私政策', terms: '服务条款' }
  },
  'EN': {
    nav: { home: 'Home', product: 'Products', cases: 'Cases', about: 'About', contact: 'Contact' },
    hero: { title1: 'AI & Energy Driven', title2: 'Zero-Carbon Operator', btn1: 'Explore Solutions', btn2: 'Learn More' },
    product: { title: 'AethraGrid', subtitle: 'AI Energy Management Cloud', tab1: '1+5 Product Matrix', tab1Desc: 'Centered on the AethraCore AI model, driving energy digital transformation with an edge-cloud architecture. Covers smart microgrid management, VPP dispatch, carbon asset management, efficiency optimization, and predictive maintenance.', tab2: 'Six-Dimensional System', tab2Desc: 'Scientific carbon calculation, source reduction, process decarbonization, intelligent control, collaborative reduction, and offset disclosure. Building a full-lifecycle carbon management system.', efficiency: 'System Efficiency', carbon: 'Real-time Reduction', ai: 'AI Dispatching', compare: 'Up 12% MoM' },
    cases: { title: 'Case Studies', subtitle: 'Global Benchmark Projects', c1: 'Solar-Storage Integration', c1c: 'Zero-Carbon Factory', c1d: 'Deployed "Solar-Storage + AI Dispatch" to achieve peak shaving and valley filling, significantly reducing electricity costs.', c2: 'Green Power + Water Cooling', c2c: 'Zero-Carbon Factory', c2d: 'Adopted "Green Power + Water Cooling + AI Dispatch" to lower cooling energy costs and increase green power usage.', c3: 'Solar + Wastewater Treatment', c3c: 'Zero-Carbon Park', c3d: 'Adopted "Solar + Load Collaborative Dispatch" to reduce operating costs and build a green demonstration park.', c4: 'German Solar-Storage-Charging', c4c: 'Zero-Carbon Park', c4d: 'Adopted "Solar-Storage-Charging + AI Dispatch" to increase energy self-sufficiency and meet European green compliance standards.' },
    data: { title: 'Value Creation', subtitle: 'Defining Zero-Carbon Productivity', s1: 'Renewable Assets Operated', s2: 'Electricity Saved', s3: 'Carbon Emission Reduced', desc: 'We provide not just solutions, but the underlying capabilities for sustainable development.' },
    map: { title: 'Global Presence', subtitle: 'Business Network', cn: 'China', us: 'USA', de: 'Germany', vn: 'Vietnam', th: 'Thailand', au: 'Australia' },
    about: { title: 'About Us', vTitle: 'Core Vision', vDesc: 'Driven by high-quality loads and AI, becoming a world-leading zero-carbon productivity operator.', pTitle: 'Core Positioning', pDesc: 'AI & Data-driven Zero-Carbon Energy Operator', fTitle: 'Focus Areas', f1: 'Low-Carbon Energy', f2: 'Lean Operations', f3: 'ESG Value Creation', cTitle: 'Customer Value', c1: 'Cost Saving', c2: 'Revenue Generation', c3: 'High Efficiency', c4: 'ESG Benchmark' },
    footer: { desc: 'Driving a low-carbon future with renewable energy and AI.', links: 'Quick Links', hq: 'Global Headquarters', sz: 'Shenzhen, China', szDesc: 'Tsinghua Information Port\nNanshan District, Shenzhen', ca: 'California, USA', caDesc: 'San Diego, California\nUSA', rights: '© 2025 AethraVolt. All rights reserved.', privacy: 'Privacy Policy', terms: 'Terms of Service' }
  },
  'DE': {
    nav: { home: 'Startseite', product: 'Produkte', cases: 'Projekte', about: 'Über uns', contact: 'Kontakt' },
    hero: { title1: 'KI & Energiegetrieben', title2: 'Zero-Carbon Betreiber', btn1: 'Lösungen entdecken', btn2: 'Mehr erfahren' },
    product: { title: 'AethraGrid', subtitle: 'KI-Energiemanagement-Cloud', tab1: '1+5 Produktmatrix', tab1Desc: 'Zentriert auf das AethraCore KI-Modell, treibt die digitale Energietransformation voran.', tab2: 'Sechs-Dimensionen-System', tab2Desc: 'Aufbau eines Kohlenstoffmanagementsystems über den gesamten Lebenszyklus.', efficiency: 'Systemeffizienz', carbon: 'Echtzeit-Reduktion', ai: 'KI-Steuerung', compare: '12% über Vormonat' },
    cases: { title: 'Projekte', subtitle: 'Globale Benchmark-Projekte', c1: 'Solar-Speicher-Integration', c1c: 'Zero-Carbon Fabrik', c1d: 'Einsatz von Solar-Speicher + KI-Steuerung zur Senkung der Stromkosten.', c2: 'Ökostrom + Wasserkühlung', c2c: 'Zero-Carbon Fabrik', c2d: 'Senkung der Energiekosten für Kühlsysteme.', c3: 'Solar + Abwasserbehandlung', c3c: 'Zero-Carbon Park', c3d: 'Reduzierung der Betriebskosten und Aufbau eines grünen Demonstrationsparks.', c4: 'Deutsches Solar-Speicher-Lade-Projekt', c4c: 'Zero-Carbon Park', c4d: 'Erhöhung der Energieautarkie und Erfüllung europäischer Umweltstandards.' },
    data: { title: 'Wertschöpfung', subtitle: 'Definition von Zero-Carbon Produktivität', s1: 'Erneuerbare Anlagen', s2: 'Eingesparter Strom', s3: 'Reduzierte CO2-Emissionen', desc: 'Wir bieten die grundlegenden Fähigkeiten für nachhaltige Entwicklung.' },
    map: { title: 'Globale Präsenz', subtitle: 'Unternehmensnetzwerk', cn: 'China', us: 'USA', de: 'Deutschland', vn: 'Vietnam', th: 'Thailand', au: 'Australien' },
    about: { title: 'Über uns', vTitle: 'Kernvision', vDesc: 'Weltweit führender Betreiber von Zero-Carbon-Produktivität werden.', pTitle: 'Positionierung', pDesc: 'KI- und datengesteuerter Zero-Carbon-Energiebetreiber', fTitle: 'Fokusbereiche', f1: 'Kohlenstoffarme Energie', f2: 'Lean Operations', f3: 'ESG-Wertschöpfung', cTitle: 'Kundennutzen', c1: 'Kosten sparen', c2: 'Umsatz generieren', c3: 'Hohe Effizienz', c4: 'ESG-Benchmark' },
    footer: { desc: 'Eine kohlenstoffarme Zukunft mit erneuerbaren Energien und KI vorantreiben.', links: 'Schnelllinks', hq: 'Hauptsitz', sz: 'Shenzhen, China', szDesc: 'Tsinghua Information Port', ca: 'Kalifornien, USA', caDesc: 'San Diego, Kalifornien', rights: '© 2025 AethraVolt. Alle Rechte vorbehalten.', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen' }
  },
  'VN': {
    nav: { home: 'Trang chủ', product: 'Sản phẩm', cases: 'Dự án', about: 'Về chúng tôi', contact: 'Liên hệ' },
    hero: { title1: 'Được thúc đẩy bởi AI & Năng lượng', title2: 'Nhà điều hành Không Carbon', btn1: 'Khám phá Giải pháp', btn2: 'Tìm hiểu thêm' },
    product: { title: 'AethraGrid', subtitle: 'Đám mây Quản lý Năng lượng AI', tab1: 'Ma trận Sản phẩm 1+5', tab1Desc: 'Tập trung vào mô hình AI AethraCore, thúc đẩy chuyển đổi số năng lượng.', tab2: 'Hệ thống Sáu chiều', tab2Desc: 'Xây dựng hệ thống quản lý carbon toàn vòng đời.', efficiency: 'Hiệu suất Hệ thống', carbon: 'Giảm phát thải thời gian thực', ai: 'AI đang điều phối', compare: 'Tăng 12% so với tháng trước' },
    cases: { title: 'Dự án', subtitle: 'Dự án Tiêu chuẩn Toàn cầu', c1: 'Tích hợp Lưu trữ Năng lượng Mặt trời', c1c: 'Nhà máy Không Carbon', c1d: 'Triển khai "Lưu trữ Năng lượng Mặt trời + Điều phối AI" để giảm chi phí điện.', c2: 'Năng lượng Xanh + Làm mát bằng Nước', c2c: 'Nhà máy Không Carbon', c2d: 'Giảm chi phí năng lượng làm mát.', c3: 'Năng lượng Mặt trời + Xử lý Nước thải', c3c: 'Khu công nghiệp Không Carbon', c3d: 'Giảm chi phí vận hành và xây dựng khu công nghiệp xanh.', c4: 'Dự án Sạc-Lưu trữ-Năng lượng Mặt trời Đức', c4c: 'Khu công nghiệp Không Carbon', c4d: 'Tăng khả năng tự túc năng lượng và đáp ứng tiêu chuẩn xanh Châu Âu.' },
    data: { title: 'Tạo Giá trị', subtitle: 'Định nghĩa Năng suất Không Carbon', s1: 'Tài sản Năng lượng Tái tạo', s2: 'Điện năng Tiết kiệm', s3: 'Giảm Phát thải Carbon', desc: 'Chúng tôi cung cấp nền tảng cho sự phát triển bền vững.' },
    map: { title: 'Hiện diện Toàn cầu', subtitle: 'Mạng lưới Kinh doanh', cn: 'Trung Quốc', us: 'Mỹ', de: 'Đức', vn: 'Việt Nam', th: 'Thái Lan', au: 'Úc' },
    about: { title: 'Về chúng tôi', vTitle: 'Tầm nhìn Cốt lõi', vDesc: 'Trở thành nhà điều hành năng suất không carbon hàng đầu thế giới.', pTitle: 'Định vị Cốt lõi', pDesc: 'Nhà điều hành năng lượng Không Carbon dựa trên AI & Dữ liệu', fTitle: 'Lĩnh vực Trọng tâm', f1: 'Năng lượng Carbon thấp', f2: 'Vận hành Tinh gọn', f3: 'Tạo giá trị ESG', cTitle: 'Giá trị Khách hàng', c1: 'Tiết kiệm Chi phí', c2: 'Tạo Doanh thu', c3: 'Hiệu quả Cao', c4: 'Tiêu chuẩn ESG' },
    footer: { desc: 'Thúc đẩy tương lai carbon thấp bằng năng lượng tái tạo và AI.', links: 'Liên kết Nhanh', hq: 'Trụ sở Toàn cầu', sz: 'Thâm Quyến, Trung Quốc', szDesc: 'Cảng Thông tin Thanh Hoa', ca: 'California, Mỹ', caDesc: 'San Diego, California', rights: '© 2025 AethraVolt. Đã đăng ký Bản quyền.', privacy: 'Chính sách Bảo mật', terms: 'Điều khoản Dịch vụ' }
  },
  'TH': {
    nav: { home: 'หน้าแรก', product: 'ผลิตภัณฑ์', cases: 'กรณีศึกษา', about: 'เกี่ยวกับเรา', contact: 'ติดต่อเรา' },
    hero: { title1: 'ขับเคลื่อนด้วย AI และพลังงาน', title2: 'ผู้ดำเนินการคาร์บอนเป็นศูนย์', btn1: 'สำรวจโซลูชัน', btn2: 'เรียนรู้เพิ่มเติม' },
    product: { title: 'AethraGrid', subtitle: 'คลาวด์การจัดการพลังงาน AI', tab1: 'เมทริกซ์ผลิตภัณฑ์ 1+5', tab1Desc: 'ขับเคลื่อนการเปลี่ยนแปลงทางดิจิทัลด้านพลังงานด้วยโมเดล AI AethraCore', tab2: 'ระบบหกมิติ', tab2Desc: 'สร้างระบบการจัดการคาร์บอนตลอดวงจรชีวิต', efficiency: 'ประสิทธิภาพระบบ', carbon: 'ลดการปล่อยคาร์บอนแบบเรียลไทม์', ai: 'AI กำลังจัดส่ง', compare: 'เพิ่มขึ้น 12% จากเดือนก่อน' },
    cases: { title: 'กรณีศึกษา', subtitle: 'โครงการมาตรฐานระดับโลก', c1: 'การรวมพลังงานแสงอาทิตย์และที่เก็บพลังงาน', c1c: 'โรงงานคาร์บอนเป็นศูนย์', c1d: 'ลดต้นทุนค่าไฟฟ้าอย่างมีนัยสำคัญ', c2: 'พลังงานสีเขียว + การทำความเย็นด้วยน้ำ', c2c: 'โรงงานคาร์บอนเป็นศูนย์', c2d: 'ลดต้นทุนพลังงานในการทำความเย็น', c3: 'พลังงานแสงอาทิตย์ + การบำบัดน้ำเสีย', c3c: 'สวนอุตสาหกรรมคาร์บอนเป็นศูนย์', c3d: 'ลดต้นทุนการดำเนินงานและสร้างสวนสาธิตสีเขียว', c4: 'โครงการชาร์จ-เก็บ-พลังงานแสงอาทิตย์ในเยอรมนี', c4c: 'สวนอุตสาหกรรมคาร์บอนเป็นศูนย์', c4d: 'เพิ่มการพึ่งพาตนเองด้านพลังงานและเป็นไปตามมาตรฐานสีเขียวของยุโรป' },
    data: { title: 'การสร้างมูลค่า', subtitle: 'กำหนดผลผลิตคาร์บอนเป็นศูนย์', s1: 'สินทรัพย์หมุนเวียนที่ดำเนินการ', s2: 'ประหยัดไฟฟ้า', s3: 'ลดการปล่อยคาร์บอน', desc: 'เราเป็นรากฐานสำหรับการพัฒนาที่ยั่งยืน' },
    map: { title: 'การแสดงตนทั่วโลก', subtitle: 'เครือข่ายธุรกิจ', cn: 'จีน', us: 'สหรัฐอเมริกา', de: 'เยอรมนี', vn: 'เวียดนาม', th: 'ไทย', au: 'ออสเตรเลีย' },
    about: { title: 'เกี่ยวกับเรา', vTitle: 'วิสัยทัศน์หลัก', vDesc: 'ก้าวสู่การเป็นผู้ดำเนินการผลผลิตคาร์บอนเป็นศูนย์ชั้นนำของโลก', pTitle: 'ตำแหน่งหลัก', pDesc: 'ผู้ดำเนินการพลังงานคาร์บอนเป็นศูนย์ที่ขับเคลื่อนด้วย AI และข้อมูล', fTitle: 'พื้นที่โฟกัส', f1: 'พลังงานคาร์บอนต่ำ', f2: 'การดำเนินงานแบบลีน', f3: 'การสร้างมูลค่า ESG', cTitle: 'คุณค่าของลูกค้า', c1: 'ประหยัดต้นทุน', c2: 'สร้างรายได้', c3: 'ประสิทธิภาพสูง', c4: 'มาตรฐาน ESG' },
    footer: { desc: 'ขับเคลื่อนอนาคตคาร์บอนต่ำด้วยพลังงานหมุนเวียนและ AI', links: 'ลิงก์ด่วน', hq: 'สำนักงานใหญ่ระดับโลก', sz: 'เซินเจิ้น, จีน', szDesc: 'Tsinghua Information Port', ca: 'แคลิฟอร์เนีย, สหรัฐอเมริกา', caDesc: 'San Diego, California', rights: '© 2025 AethraVolt. สงวนลิขสิทธิ์.', privacy: 'นโยบายความเป็นส่วนตัว', terms: 'เงื่อนไขการให้บริการ' }
  }
};
